main: ${group}.${name}.${name}
api-version: ${apiVersion}

name: ${name}
version: ${version}
author: ${author}

softdepend: [PlaceholderAPI]

commands:
  brightstpa:
    description: Reload the config or check version
  tpa:
    description: TPA to a player
  tpahere:
    description: TPA a player to you
  tpaccept:
    description: Accept a TPA request
    aliases: [tpyes]
  tpdeny:
    description: Deny a TPA request
    aliases: [tpno]
  tpacancel:
    description: Cancel all requests

permissions:
  brightstpa.bypass.tpdelay:
    default: op
  brightstpa.bypass.cooldown.command:
    default: op
  brightstpa.bypass.cooldown.request:
    default: op
  brightstpa.admin:
    default: op
  brightstpa.tpdeny:
    default: true
  brightstpa.tpaccept:
    default: true
  brightstpa.tpa:
    default: true
  brightstpa.tpahere:
    default: true
  brightstpa.tpacancel:
    default: true
  brightstpa.*:
    default: false
    children:
      brightstpa.bypass.tpdelay: true
      brightstpa.bypass.cooldown.command: true
      brightstpa.bypass.cooldown.request: true
      brightstpa.admin: true
      brightstpa.tpdeny: true
      brightstpa.tpaccept: true
      brightstpa.tpa: true
      brightstpa.tpahere: true
      brightstpa.tpacancel: true
